# Generated by Django 4.0.5 on 2022-06-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='products/%y/%m/%d'),
        ),
    ]
