# Generated by Django 4.0.5 on 2022-06-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cartItem',
            new_name='cartItems',
        ),
    ]
