# Generated by Django 4.0.5 on 2022-06-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_cartitem_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartItems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cart.cartitem'),
        ),
    ]
